### ISSUE TITLE
videos downloaded would the post title in the file name.

### ISSUE THREAD

**Issue by Goldmaster** [JohannesPertl/vreddit-download-bot#13]
Rather have a file as ripsave - awbgxapj34i4.mp4 it would be useful if it would download as This parody of the anti piracy ad by the lads over at r.historymemes.mp4 along with it in the title properties along with link to video on reddit, OP ect.

**Comment by JohannesPertl** [comment]
Sorry that is not possible, the bot only uses ripsave as a service, which provides the mp4 file. You could [contact them](https://ripsave.com/contact) directly and ask them to implement this feature :)
