### ISSUE TITLE
vreddit.cc hosted video files are returning 500 Internal Server Error

### ISSUE THREAD

**Issue by kouwei32** [JohannesPertl/vreddit-download-bot#17]
Here's an example link that does not work for me: [https://vreddit.cc/hkrty3ghzcf11](https://vreddit.cc/hkrty3ghzcf11)

Note, the HTML and the thumbnail still loads, but the video file resource does not, and will not play or download.
<img width="456" alt="Console Output" src="https://user-images.githubusercontent.com/29967594/77362841-e9573e00-6d0e-11ea-8b3f-6f0eac52a773.png">

**Comment by frapbod** [comment]
Just wanted to add on I’m also unable to download anything hosted on vreddit.cc while using safari on iPhone.

**Comment by JohannesPertl** [comment]
I stopped using vreddit.cc, as it also got blacklisted on reddit
