### ISSUE TITLE
Direct audio + sound

### ISSUE THREAD

**Issue by aviyadeveloper** [JohannesPertl/vreddit-download-bot#2]
Right now it provides:

- direct video without sound.
- direct audio
- download video + audio

I think a version providing the video + audio in a stream and **shareable** (why reddit why is this not possible.....) would be great.

I would argue that there's not much work left to be done since the actual united version is produced already, so it's mainly about finding the right platform for uploading it to and then harvesting the link.

**Comment by aviyadeveloper** [comment]
Now as a comment, I would be happy to contribute for this if you want. But if it's like your personal project and stuff no problem!

**Comment by JohannesPertl** [comment]
I appreciate any help I can get get, thanks! 
I don't have a lot of time at the moment, but I plan to refactor the code before adding any additional functionality, as I didn't know a lot about python when I started writing the bot. 

Uploading to an external site is already implemented though. 
The bot used streamable, mixtape.moe, catbox.moe and vredd.it in the past, but was either IP banned (I host it myself) or the site was shut down, so all that's working now is ripsave.com.
