### ISSUE TITLE
Bot Authenticates but doesn't detect comments or DM's

### ISSUE THREAD

**Issue by Shmnel** [JohannesPertl/vreddit-download-bot#23]
Like the title says the bot will sign in and authenticate but will not detect DM's or comments of it being mentioned

**Comment by JohannesPertl** [comment]
Did you fill in the name of your bot in the config.yaml?

**Comment by undefinedText** [comment]
Yes I have filled the bots name in config

**Comment by undefinedText** [comment]
After restarting the bot for another time it seems to have noticed all of the DM's and mentions and is starting to send them out. Sorry for wasting your time.
