### ISSUE TITLE
upload_via_ripsave not working since recent website change

### ISSUE THREAD

**Issue by JCA122204** [JohannesPertl/vreddit-download-bot#6]
What is the issue you referred to in your post yesterday. I want to help if you can't fix it now.

**Comment by JohannesPertl** [comment]
Thanks! The script mainly used https://ripsave.com to provide links, but the owner recently changed the website, so my way of accessing the video link doesn't work anymore (via selenium). The functionality is provided in upload_via_ripsave(). If you can find a way to fix it (maybe using basic http requests and posts, or selenium, or both) that would be great!

**Comment by ptoews** [comment]
Currently, the ripsave links seem to work: https://www.reddit.com/user/VredditDownloader/
Is this still an issue? Or doesn't it occur every time?

**Comment by JohannesPertl** [comment]
I wrote a quick fix just a few minutes before your comment ;) I just updated the repo, so the issue should be resolved for now, but feel free to improve my solution, it's a bit smelly

**Comment by JohannesPertl** [comment]
My quick fix didn't really fix the issue apparently. As ripsave only hosts the file for a few minutes, the link my bot posts doesn't lead anywhere after that time.

**Comment by ptoews** [comment]
Just wondering: Why is ripsave so important? Aren't there two alternative providers?

**Comment by JohannesPertl** [comment]
I previously used http://vredd.it, but it's offline now. The only other provider is http://lew.la, but I limited uploading to 100 videos/day per request of the owner.
